# Generated by Django 3.0.5 on 2020-06-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200515_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='uploads/user/profile_pic'),
        ),
    ]
