# Generated by Django 3.0.5 on 2020-06-11 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_profile_pic'),
        ('users', '0005_auto_20200604_1539'),
    ]

    operations = [
    ]
