# Generated by Django 3.0.5 on 2020-04-20 23:53

from django.db import migrations, models
import org.custom_model_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perm', org.custom_model_field.PermissionSetField(default='', max_length=8196, null=True)),
            ],
        ),
    ]
