# Generated by Django 3.0.5 on 2020-04-21 08:20

from django.db import migrations
import org.custom_model_field


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_auto_20200421_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='perm',
            field=org.custom_model_field.PermissionSetField(default='', max_length=8196, null=True),
        ),
    ]
