# Generated by Django 3.0.5 on 2020-05-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_auto_20200505_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='can_join_without_invite',
            field=models.BooleanField(default=True),
        ),
    ]
