# Generated by Django 3.0.5 on 2020-05-06 20:47

from django.db import migrations, models
import org.custom_model_field


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0004_auto_20200505_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionSetTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perm', org.custom_model_field.PermissionField()),
            ],
        ),
        migrations.AddField(
            model_name='permissionset',
            name='name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='invite_slug',
            field=models.SlugField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='org',
            name='about',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='org',
            name='cover_pic',
            field=models.ImageField(null=True, upload_to='uploads/org/cover_pic'),
        ),
        migrations.AlterField(
            model_name='org',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='org',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='uploads/org/profile_pic'),
        ),
        migrations.AlterField(
            model_name='org',
            name='route_slug',
            field=models.SlugField(max_length=40, unique=True),
        ),
    ]
