# Generated by Django 3.0.5 on 2020-05-24 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_auto_20200506_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='permissions',
            new_name='permission_set',
        ),
        migrations.RenameField(
            model_name='permissionset',
            old_name='permissions',
            new_name='perm_obj',
        ),
    ]
