# Generated by Django 3.0.5 on 2020-05-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0006_auto_20200528_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='default_permissions',
            new_name='perm_obj',
        ),
    ]
