# Generated by Django 3.0.5 on 2020-05-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='share_img',
            field=models.ImageField(null=True, upload_to='uploads/tasks/share_img'),
        ),
        migrations.AlterField(
            model_name='task',
            name='share_link',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='share_text',
            field=models.CharField(max_length=65536, null=True),
        ),
    ]
