# Generated by Django 3.0.5 on 2020-06-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200609_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='share_link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
